### ISSUE TITLE
Make delim a keyword argument

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/CSVFiles.jl#16]

**Comment by zweiglimmergneis** [comment]
It would be really good, having `load` working properly with `delim` as a keyword argument, as it is claimed in the documentation. Let me know if this can be done in reasonable time by a person like me, working with julia at a user level until now.

**Comment by davidanthoff** [comment]
Yes, this should actually be a really simple change: we just have to change the four ``fileio_load`` functions [here](https://github.com/queryverse/CSVFiles.jl/blob/master/src/CSVFiles.jl#L41) so that ``delim`` is no longer an optional, but instead a keyword argument.

And then update tests etc., but in general this should be a simple change. A PR would be very welcome!
