### ISSUE TITLE
DataFrame() cannot convert load("*.csv") using pmap

### ISSUE THREAD

**Issue by alberthaoh** [queryverse/CSVFiles.jl#19]
When using pmap, DataFrame(load("*.csv")) does not work. worker returns convert error, cannot convert CSVFiles.CSVFiles to DataFrames.DataFrame. Works fine when using without pmap.

**Comment by davidanthoff** [comment]
I’ll try later on my machine, but I suspect it is somehow related to a missing package load. Can you try to manually load IterableTables on the workers?

**Comment by alberthaoh** [comment]
Hi, thanks for the reply. I don't have time to test that now, I forced to use readtable for now^.^.  I can probably test it later, thanks a lot!

**Comment by davidanthoff** [comment]
The whole ``DataFrame`` constructor story has changed, please report if this still doesn't work!
