### ISSUE TITLE
Feature request: return data on save

### ISSUE THREAD

**Issue by CiaranOMara** [queryverse/CSVFiles.jl#45]
I think it would be useful if the save method returned its given data. This change would allow variable assignment after chaining/continuations. 

For Example:
```julia
using FileIO, CSVFiles
using DataFrames
using Query
using Test

df = DataFrame([(a=1,b=2),(a=3,b=4)])
result = df |> @map({e = _.a^2}) |> DataFrame |> save("tmp.csv") 
@test result[2,1] == 9
```

Let me know what you think, or if you foresee any other issues that may have passed me.

**Comment by davidanthoff** [comment]
You can use the `@tee` macro from the [Queryverse.jl](https://github.com/queryverse/Queryverse.jl) package for this:
```julia
result = df |> @map({e = _.a^2}) |> DataFrame |> @tee(save("tmp.csv"))
```

**Comment by CiaranOMara** [comment]
That's a nice [macro](https://github.com/queryverse/Queryverse.jl/blob/7ea11cdc87f10d3f62dafc06ab49f0dd226f451e/src/Queryverse.jl#L23-L30).

**Comment by davidanthoff** [comment]
I wish we had proper syntax for this in julia for this: https://github.com/JuliaLang/julia/issues/25233

**Comment by CiaranOMara** [comment]
I think this may be a possible variant of @tee.

```julia
function tee(func::Function)
    data -> (data |> func; data)
end

result = df |> @map({e = _.a^2}) |> DataFrame |> tee(save("tmp.csv"))
```

**Comment by CiaranOMara** [comment]
I also had a quick look through the docs for a `tee` function or something of the like. Unfortunately, I didn't find any such thing. It'd be great if something of the sort were in `Base`.

**Comment by CiaranOMara** [comment]
I think this may be a possible variant of your [@tee](https://github.com/queryverse/Queryverse.jl/blob/7ea11cdc87f10d3f62dafc06ab49f0dd226f451e/src/Queryverse.jl#L23-L30).

```julia
function tee(func::Function)
    data -> (data |> func; data)
end

result = df |> @map({e = _.a^2}) |> DataFrame |> tee(save("tmp.csv"))
```
