### ISSUE TITLE
Add example of how to read CSV files and specify a delimiter

### ISSUE THREAD

**Issue by xiaodaigh** [queryverse/CSVFiles.jl#50]
I can never figure out how to set the delim reading the readme. 

It would good to actually add an example instead of just having the signature.

I tried

```juli
FileIO.File(format"CSV", delim='|')

FileIO.File(format"CSV"(delim='|'))
```
neither worked.

**Comment by davidanthoff** [comment]
The real issue is that for really no good reason `delim` is not a keyword argument, but a positional argument. I think that is the thing we should actually really change.

**Comment by xiaodaigh** [comment]
So given where we are at, how do I set the `delim`?

**Comment by davidanthoff** [comment]
Right now? Just the second argument: `load("foo.csv", ';')`.

**Comment by xgdgsc** [comment]
What if the file suffix isn' t ".csv"?

**Comment by davidanthoff** [comment]
I believe `load(File(format"CSV", filename))`.

**Comment by xiaodaigh** [comment]
full working example
```julia
using DataFrames, CSV

CSV.write("a.txt", DataFrame(a=1:3, b = 1:3), delim='|', writeheader=false)

using FileIO, CSVFiles

@time a = load(File(format"CSV", "a.txt"), '|', header_exists=false) |> DataFrame
```
