### ISSUE TITLE
Deprecation warning at TableTraitsUtils.jl:17

### ISSUE THREAD

**Issue by DevJac** [queryverse/CSVFiles.jl#69]
I get the following warning when loading a CSV file with Julia 1.2.
```
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = create_tableiterator(::Array{Array{T,1} where T,1}, ::Array{Symbol,1}) at TableTraitsUtils.jl:17
└ @ TableTraitsUtils ~/.julia/packages/TableTraitsUtils/IAE6S/src/TableTraitsUtils.jl:17
```
Looks easy to fix (famous last words). If nobody else can get to it, I'd be willing to make the change with a little encouragement. :wink:

**Comment by davidanthoff** [comment]
Should be fixed once this is merged: https://github.com/JuliaRegistries/General/pull/5666. Thanks for reporting!
